# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Neighboorhood-iOS-Services' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'IQKeyboardManagerSwift'
pod 'Alamofire', '~> 4.8.2'
pod 'MBProgressHUD'
pod 'SwiftyJSON'
pod 'FSCalendar'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'Cosmos'
pod 'SDWebImage'
#pod 'JSQMessagesViewController'
pod 'BRYXBanner'
pod 'STZPopupView'
pod 'ReachabilitySwift'
pod 'Socket.IO-Client-Swift', '~> 11.1.3'
pod 'SideMenu', '~> 6.0'
pod 'GrowingTextView'
pod 'ReverseExtension'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'SVProgressHUD'
pod 'SKCountryPicker'
pod 'SwiftPopup', '~> 4.2.0'
pod 'Kingfisher'#, :git => 'https://github.com/onevcat/Kingfisher.git', :branch => "master"

  # Pods for Neighboorhood-iOS-Services

  target 'Neighboorhood-iOS-ServicesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Neighboorhood-iOS-ServicesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
